name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev
    - name: Run tests
      run: |
        pipenv run pytest tests/
    - name: Run linting
      run: |
        pipenv run flake8 src/
    - name: Upload plot artifacts
      uses: actions/upload-artifact@v2
      with:
        name: plots
        path: image/